/// Flutter icons HeirAppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HeirAppIcons
///      fonts:
///       - asset: fonts/HeirAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HeirAppIcons {
  HeirAppIcons._();

  static const _kFontFam = 'HeirAppIcons';
  static const String? _kFontPkg = null;

  static const IconData angle_left = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_small_right = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beneficiary = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btc_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_24px = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_rr_comment_alt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_rr_sign_out = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finances1_27 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_rr_menu_dots_vertical = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finances = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconoir_scan_qr_code = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eth_icon = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_outline_24px = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_none_24px = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fi_rr_cross_circle = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
